log-level: silent
allow-lan: true
redir-port: 5000
tproxy-port: 5001
ipv6: true
mode: rule
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile: { store-selected: true }
geo-auto-update: true
geo-update-interval: 72

sniffer:
  enable: true
  sniff:
    HTTP:
    TLS:
    QUIC:

anchors:
  a1: &domain { type: http, format: mrs, behavior: domain, interval: 86400 }
  a2: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400 }
  a3: &classical { type: http, format: text, behavior: classical, interval: 86400 }
  a4: &inline { type: inline, behavior: classical }

dns:
  enable: false

proxy-providers:
  pqsubscribe:
    type: http
    url: https://ваша_ссылка_подписки
    interval: 3600
    proxy: DIRECT
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204

proxy-groups:
  - name: MAIN-MODE
    type: select
    proxies:
    - PROXY-AUTO
    - PROXY-MANUAL
    - DIRECT

  - name: PROXY-AUTO
    type: fallback
    proxies:
      - PROXY-LOAD-BALANCE
      - PROXY-FAILOVER
      - DIRECT
    url: http://cp.cloudflare.com/generate_204
    expected-status: 204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true

  - name: PROXY-LOAD-BALANCE
    type: load-balance
    use:
      - pqsubscribe
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    strategy: consistent-hashing
    expected-status: 204
    tolerance: 150
    lazy: true
    hidden: true

  - name: PROXY-FAILOVER
    type: fallback
    use:
      - pqsubscribe
    url: http://cp.cloudflare.com/generate_204
    expected-status: 204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true

  - name: PROXY-MANUAL
    type: select
    lazy: true
    use:
      - pqsubscribe

  - name: GLOBAL
    type: select
    hidden: true
    proxies:
      - PROXY-AUTO
      - PROXY-MANUAL
      - PROXY-LOAD-BALANCE
      - PROXY-FAILOVER
      - DIRECT

  - name: QUIC
    type: select
    hidden: true
    proxies:
      - REJECT
      - PASS

rule-providers:
  amazon@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/amazon.mrs }
  amazon@ipcidr: { <<: *ipcidr, url: https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/amazon.mrs }
  category-ai@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs }
  cloudflare@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cloudflare.mrs }
  cloudflare@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cloudflare.mrs }
  discord@classical: { <<: *classical, url: https://github.com/zxc-rv/assets/raw/main/rules/discord.list }
  google@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google.mrs }
  github@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/github.mrs }
  meta@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/facebook.mrs }
  meta@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/facebook.mrs }
  reddit@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs }
  refilter@domain: { <<: *domain, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs }
  spotify@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/spotify.mrs }
  steam@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/steam.mrs }
  telegram@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs }
  telegram@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs }
  twitch@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitch.mrs }
  twitter@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitter.mrs }
  youtube@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs }
  rubundle@domain: { <<: *domain, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/ru-bundle/rule.mrs }
  legizdiscord@ipcidr: { <<: *ipcidr, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/discord-voice-ip-list.mrs }


rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),QUIC
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve

  - DOMAIN-KEYWORD,huuli.art,DIRECT
  - DOMAIN-KEYWORD,petqa.ru,DIRECT
  - DOMAIN-KEYWORD,cp.cloudflare.com,DIRECT

  - DOMAIN,ip.flant.ru,MAIN-MODE

  - DOMAIN-KEYWORD,trae,MAIN-MODE
  - DOMAIN-KEYWORD,fellow,MAIN-MODE
  - DOMAIN-KEYWORD,docker,MAIN-MODE
  - DOMAIN-KEYWORD,discord,MAIN-MODE
  - DOMAIN-KEYWORD,redhat,MAIN-MODE
  - DOMAIN-KEYWORD,openshift,MAIN-MODE

  - DOMAIN,sites.google.com,DIRECT

  - DOMAIN-SUFFIX,dev,MAIN-MODE
  - DOMAIN-SUFFIX,org,MAIN-MODE
  - DOMAIN-SUFFIX,io,MAIN-MODE
  - DOMAIN-SUFFIX,ai,MAIN-MODE
  - DOMAIN-SUFFIX,to,MAIN-MODE
  - DOMAIN-SUFFIX,one,MAIN-MODE
  - DOMAIN-SUFFIX,sh,MAIN-MODE
  - DOMAIN-SUFFIX,pro,MAIN-MODE
  - DOMAIN-SUFFIX,app,MAIN-MODE

  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),MAIN-MODE
  - RULE-SET,category-ai@domain,MAIN-MODE
  - RULE-SET,steam@domain,MAIN-MODE
  - RULE-SET,spotify@domain,MAIN-MODE
  - RULE-SET,reddit@domain,MAIN-MODE
  - RULE-SET,youtube@domain,MAIN-MODE
  - RULE-SET,twitch@domain,MAIN-MODE
  - RULE-SET,twitter@domain,MAIN-MODE
  - RULE-SET,discord@classical,MAIN-MODE
  - OR,((RULE-SET,meta@domain),(RULE-SET,meta@ipcidr,no-resolve)),MAIN-MODE
  - OR,((RULE-SET,telegram@domain),(RULE-SET,telegram@ipcidr,no-resolve)),MAIN-MODE
  - OR,((RULE-SET,cloudflare@domain),(RULE-SET,cloudflare@ipcidr)),MAIN-MODE
  - OR,((RULE-SET,amazon@domain),(RULE-SET,amazon@ipcidr)),MAIN-MODE
  - RULE-SET,refilter@domain,MAIN-MODE
  - RULE-SET,google@domain,MAIN-MODE
  - RULE-SET,github@domain,MAIN-MODE

  - MATCH,DIRECT